-- mysql -h 127.0.0.1 -uspider -pspider < temp.sql

USE 3GTEST_NEW;


DROP TABLE IF EXISTS CONFIG_TERMINAL_ROUTINE;
CREATE TABLE CONFIG_TERMINAL_ROUTINE (
			TERMINAL_ID   VARCHAR(20) NOT NULL,
			STARTTIME     VARCHAR(16) NOT NULL,
			TYPE          VARCHAR(32) NOT NULL,
			FLAG_CDMA     VARCHAR(1) NOT NULL DEFAULT 'F',
			PRIMARY KEY  (TERMINAL_ID, STARTTIME)
			) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CONFIG_TERMINAL_ROUTINE_BK;
CREATE TABLE CONFIG_TERMINAL_ROUTINE_BK LIKE CONFIG_TERMINAL_ROUTINE;
