-- mysql -h 127.0.0.1 -uspider -pspider < terminal_routine.sql

USE 3GTEST_NEW;

DELETE FROM CONFIG_TERMINAL_ROUTINE;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_PING;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_HTTP;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_FTP;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_CQT;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_EXTRA_PESQ;

DELETE FROM CONFIG_TERMINAL_ROUTINE_BK;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_PING_BK;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_HTTP_BK;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_FTP_BK;
DELETE FROM CONFIG_TERMINAL_ROUTINE_CONTENT_CQT_BK;

INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '11:15', 'PING', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '11:19', 'HTTP', 'T');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '11:16', 'FTP', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '11:26', 'CQT', 'T');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '11:27', 'PESQ', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '0:00', 'Restart', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '0:30', 'upload', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '1:30', 'upload', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '12:00', 'heartbeat', 'F');
INSERT INTO CONFIG_TERMINAL_ROUTINE(TERMINAL_ID, STARTTIME, TYPE, FLAG_CDMA) 
                        VALUES('18916528506', '12:20', 'CDMAPARA', 'F');
                               
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_PING(TERMINAL_ID, STARTTIME, TIMES, PACKSIZE, TM_INTER, TMOUT, URL) 
                        VALUES('18916528506', '11:15', '3', '50', '2', '10', 'www.google.com');
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_HTTP(TERMINAL_ID, STARTTIME, TIMES, TMOUT, URL) 
                        VALUES('18916528506', '11:19', '10', '10', 'http://www.vckbase.com');
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_FTP(TERMINAL_ID, STARTTIME, TIMES, TMOUT, URL, DIRECTION, NUMBER_PROCESS) 
                        VALUES('18916528506', '11:16', '3', '10', 'ftp://symtree:jason010101@222.186.191.102/wwwroot/B/BaseTech.lib', '1', '1');
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_CQT(TERMINAL_ID, STARTTIME, TYPE, TM_INTER, TIMES, TEST_TMINTER, TEST_TIMES, TM_CALLHOLD) 
                        VALUES('18916528506', '11:26', '1', '10', '3', '5', '1', '15');
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_EXTRA_PESQ(TERMINAL_ID, STARTTIME, TYPE, SRCFNAME, EXEC_DATA) 
                        VALUES('18916528506', '11:27', '1', 'AGMA1M02.wav', '20091201');

INSERT INTO CONFIG_TERMINAL_ROUTINE_BK SELECT * FROM CONFIG_TERMINAL_ROUTINE;
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_PING_BK SELECT * FROM CONFIG_TERMINAL_ROUTINE_CONTENT_PING;
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_HTTP_BK SELECT * FROM CONFIG_TERMINAL_ROUTINE_CONTENT_HTTP;
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_FTP_BK SELECT * FROM CONFIG_TERMINAL_ROUTINE_CONTENT_FTP;
INSERT INTO CONFIG_TERMINAL_ROUTINE_CONTENT_CQT_BK SELECT * FROM CONFIG_TERMINAL_ROUTINE_CONTENT_CQT;

